"""add_embedding_version_and_session_id_to_analyses

Revision ID: 1523ca7823f3
Revises: 68374d89cf81
Create Date: 2026-09-25 22:45:47.919692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1523ca7823f3'
down_revision: Union[str, Sequence[str], None] = '68374d89cf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_version', sa.String(length=50), nullable=False, server_default='v1.0.0'))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_analyses_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_session_id'))
        batch_op.drop_column('session_id')
        batch_op.drop_column('embedding_version')

    # ### end Alembic commands ###
