"""Canonical taxonomy dictionary mapping variants and aliases to standardized canonical names."""

from typing import Dict, Set

# Map aliases/variations -> canonical skill name
CANONICAL_SKILL_MAP: Dict[str, str] = {
    # Programming Languages
    "python": "python",
    "python 3": "python",
    "python3": "python",
    "py": "python",
    "javascript": "javascript",
    "js": "javascript",
    "ecmascript": "javascript",
    "es6": "javascript",
    "es2015": "javascript",
    "typescript": "typescript",
    "ts": "typescript",
    "java": "java",
    "golang": "go",
    "go lang": "go",
    "go": "go",
    "c++": "c++",
    "cpp": "c++",
    "c#": "c#",
    "csharp": "c#",
    ".net": ".net",
    "dotnet": ".net",
    ".net core": ".net",
    "asp.net": "asp.net",
    "ruby": "ruby",
    "php": "php",
    "rust": "rust",
    "scala": "scala",
    "kotlin": "kotlin",
    "swift": "swift",
    "r": "r",

    # Web & API Frameworks
    "react": "react",
    "react.js": "react",
    "reactjs": "react",
    "next.js": "next.js",
    "nextjs": "next.js",
    "vue": "vue",
    "vue.js": "vue",
    "vuejs": "vue",
    "angular": "angular",
    "angularjs": "angular",
    "node": "node.js",
    "node.js": "node.js",
    "nodejs": "node.js",
    "fastapi": "fastapi",
    "django": "django",
    "flask": "flask",
    "spring": "spring",
    "spring boot": "spring boot",
    "express": "express.js",
    "express.js": "express.js",
    "expressjs": "express.js",

    # Databases & Storage
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "pgsql": "postgresql",
    "mysql": "mysql",
    "sqlite": "sqlite",
    "sqlite3": "sqlite",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "redis": "redis",
    "cassandra": "cassandra",
    "elasticsearch": "elasticsearch",
    "opensearch": "opensearch",
    "dynamodb": "dynamodb",
    "sql": "sql",
    "nosql": "nosql",

    # Cloud, DevOps & Infrastructure
    "aws": "aws",
    "amazon web services": "aws",
    "gcp": "gcp",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "azure": "azure",
    "microsoft azure": "azure",
    "docker": "docker",
    "containerization": "docker",
    "containers": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "terraform": "terraform",
    "ansible": "ansible",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "continuous integration": "ci/cd",
    "github actions": "github actions",
    "jenkins": "jenkins",
    "linux": "linux",
    "git": "git",

    # Messaging & Architecture
    "kafka": "apache kafka",
    "apache kafka": "apache kafka",
    "rabbitmq": "rabbitmq",
    "rest": "rest api",
    "rest api": "rest api",
    "restful api": "rest api",
    "restful apis": "rest api",
    "rest apis": "rest api",
    "graphql": "graphql",
    "grpc": "grpc",
    "microservices": "microservices",

    # Data Science & Machine Learning
    "machine learning": "machine learning",
    "ml": "machine learning",
    "artificial intelligence": "artificial intelligence",
    "ai": "artificial intelligence",
    "deep learning": "deep learning",
    "natural language processing": "nlp",
    "nlp": "nlp",
    "large language models": "llm",
    "llm": "llm",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "pandas": "pandas",
    "numpy": "numpy",
}

# Critical sets that must NEVER be conflated
UNRELATED_PAIRS_CHECK: Set[frozenset] = {
    frozenset(["java", "javascript"]),
    frozenset(["c", "c++"]),
    frozenset(["c", "c#"]),
    frozenset(["c++", "c#"]),
    frozenset(["sql", "nosql"]),
    frozenset(["python", "r"]),
}
