"""Base abstract provider contracts for LLM and Embedding services."""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    """Normalized response envelope from any LLM provider."""
    content: str = Field(..., description="Raw text generated by model")
    structured_data: Optional[Dict[str, Any]] = Field(None, description="Validated JSON payload if JSON mode requested")
    provider: str = Field(..., description="Provider identifier, e.g. openai, ollama, mock")
    model: str = Field(..., description="Model identifier used for inference")
    input_tokens: int = Field(default=0)
    output_tokens: int = Field(default=0)
    latency_ms: float = Field(default=0.0)


class BaseLLMProvider(ABC):
    """Abstract interface for LLM text and structured JSON generation."""

    @abstractmethod
    async def generate_text(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        temperature: float = 0.0,
        max_tokens: int = 2000,
    ) -> LLMResponse:
        """Generates text from prompt."""
        pass

    @abstractmethod
    async def generate_structured(
        self,
        prompt: str,
        schema: type[BaseModel],
        system_prompt: Optional[str] = None,
        temperature: float = 0.0,
    ) -> LLMResponse:
        """Generates structured output strictly conforming to the provided Pydantic schema."""
        pass


class BaseEmbeddingProvider(ABC):
    """Abstract interface for generating vector embeddings."""

    @abstractmethod
    async def get_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Generates floating-point embedding vectors for a list of texts."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Returns embedding model name."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Returns vector dimensionality."""
        pass
